### ISSUE TITLE
Cannot reach the website in arch linux 

### ISSUE THREAD

**Issue by prorounak2005** [chrisx8/simple-personal-site#185]
I am facing a weird problem. I can reach the website chrisx.xyz in windows but when I try linux distros such as linux mint and manjaro I cannot reach the website https://chrisx.xyz and firefox says that "Connection has timed out" any clue ? 

![2022-03-12_21-59](https://user-images.githubusercontent.com/69617708/158026263-67782a79-6635-4af5-965c-8ab51f5c8b4d.png)

**Comment by prorounak2005** [comment]
I already made a post on arch linux forums but the problem still persists - https://bbs.archlinux.org/viewtopic.php?id=274042

**Comment by chrisx8** [comment]
Hello @prorounak2005,

I took a look at the thread on the Arch forums, and to me it does look like there are some issues with your Arch system.

As [chrisx.xyz](https://chrisx.xyz) uses Cloudflare, I would also recommend checking if you can reach any other websites using Cloudflare. There are many websites using Cloudflare, [cloudflare.com](https://cloudflare.com) is one of them.

By the way, I'm closing this issue here, because this issue tracker is for my simple-personal-site project, ***not*** [chrisx.xyz](https://chrisx.xyz) (my website).
